export const CLOSE_MODAL = 'CLOSE_MODAL';
export const OPEN_PLACE_MODAL = 'OPEN_PLACE_MODAL';
export const OPEN_DELETE_ITEM_MODAL = 'OPEN_DELETE_ITEM_MODAL';
export const OPEN_INFO_MODAL = ' OPEN_INFO_MODAL';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_TOKEN_LOGIN = 'USER_TOKEN_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_DELETED_PLACE = 'USER_DELETED_PLACE';
// export const USER_ADD_PLACE = 'USER_ADD_PLACE';
